### ISSUE TITLE
Error occurred when trying to run 'snf --name 'conv1x1_glow_cifar''

### ISSUE THREAD

**Issue by Donglin-Wang2** [akandykeller/SelfNormalizingFlows#1]
I successfully cloned and created the environment for your repository. I have also run the 'snf --name 'selfnorm_fc_mnist'' command without any problem. However, when I was trying to run 'snf --name 'conv1x1_glow_cifar'', the following error occurred:

```
Emitting ninja build file /home/donglin/Github/SelfNormalizingFlows/snf/utils/convbackward/torch_cpp_extensions/build.ninja...
Building extension module conv2d_backward...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module conv2d_backward...
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to ./data/cifar-10-python.tar.gz
100.0%Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified
Warning: No checkpoint path specified, defaulting to ./3L-32K_Glow_Exact_CIFAR_checkpoint.tar
Epoch: 0
Best Val LogPx: -inf
Test LogPx: -inf
Epoch: 1

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.

Intel MKL ERROR: Parameter 4 was incorrect on entry to SLASCL.
Traceback (most recent call last):
  File "/home/donglin/anaconda3/envs/snf/bin/snf", line 33, in <module>
    sys.exit(load_entry_point('SelfNormalizingFlow', 'console_scripts', 'snf')())
  File "/home/donglin/Github/SelfNormalizingFlows/snf/cli.py", line 19, in main
    experiment.main()
  File "/home/donglin/Github/SelfNormalizingFlows/snf/experiments/conv1x1_glow_cifar.py", line 86, in main
    experiment.run()
  File "/home/donglin/Github/SelfNormalizingFlows/snf/train/experiment.py", line 92, in run
    avg_loss = self.train_epoch(e)
  File "/home/donglin/Github/SelfNormalizingFlows/snf/train/experiment.py", line 163, in train_epoch
    lossval.backward()
  File "/home/donglin/anaconda3/envs/snf/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/donglin/anaconda3/envs/snf/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: svd_cuda: the updating process of SBDSDC did not converge (error: 22)
```

I am not sure why this is the case. What have I missed in the installation process that led to this error?

**Comment by akandykeller** [comment]
Hi Donglin-Wang, I am not sure this is related to installation. I think this is likely just due to a numerical instability at some point early on in training (although I suppose this could be related to hardware or MKL/CUDA versions). If you change the 'log_interval' [here](https://github.com/akandykeller/SelfNormalizingFlows/blob/9feebb36255c5947aec1c58acd91be79135aabe8/snf/experiments/conv1x1_glow_cifar.py#L53) to 1 or 10 you will probably see a few loss logs before it crashes. This can probably be fixed more permanently by adding gradient clipping (setting it to >0 in the config), reducing the 'warmup_epochs', or using a different weight initialization. However, it also seems to eventually work for me if I just attempt to run it a few times. Once the model passes the first ~100 batches it seems to be stable. Please let me know if you can't manage to get any stable runs and I can try some more permanent fixes.

**Comment by akandykeller** [comment]
Closing due to no response
