### ISSUE TITLE
Issues about reproducing the results of 'exact_fc_mnist'

### ISSUE THREAD

**Issue by chen-hao-chao** [akandykeller/SelfNormalizingFlows#2]
Hi,

Thanks for your excellent work and released code implementation. 

I was trying to reproduce the result of the baseline method (i.e., 'exact_fc_mnist') in Table 1. However, the testing log probability is around 1036 at the 2000-th epoch, which is quite different from that (i.e., around 962) in Figure 5. I am thinking if you could help me with this issue?

Thank you very much.

**Comment by akandykeller** [comment]
Hi Lance,

Thank you for bringing my attention to this. It appears there was some change with the last commit which changed the performance of this experiment. If you revert to the prior commit (https://github.com/akandykeller/SelfNormalizingFlows/commit/3e5b606968275d5a16689e654d6ad10b6c064413) you indeed should get around 962. 

I'm currently investigating what exactly caused the change and will update here when I find it!

Thanks,
Andy

**Comment by akandykeller** [comment]
Hi Lance, 

Thanks for finding this! Apparently the difference in performance was due to a change of initialization I had for the FC layers which I did not push originally. 

I've now added it to the latest commit, so pulling this change should now get you >-960 performance. 

I'll go ahead and close this issue now, but please feel free to open another or let me know if it is still not working for you!

Best,
Andy
